version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trader
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  trader:
    image: trader:latest
    ports:
      - "3000:3000"
    build: ./

volumes:
  db-data:
